<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Profman_m extends CI_Model
{

    public $table = 'profesores';
    public $id = 'Codigo';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('Codigo', $q);
	$this->db->or_like('TomaPosesion', $q);
	$this->db->or_like('Puesto', $q);
	$this->db->or_like('Apellido1', $q);
	$this->db->or_like('Apellido2', $q);
	$this->db->or_like('Nombre', $q);
	$this->db->or_like('Sustituto', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('Codigo', $q);
	$this->db->or_like('TomaPosesion', $q);
	$this->db->or_like('Puesto', $q);
	$this->db->or_like('Apellido1', $q);
	$this->db->or_like('Apellido2', $q);
	$this->db->or_like('Nombre', $q);
	$this->db->or_like('Sustituto', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Profman_m.php */
/* Location: ./application/models/Profman_m.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-02-26 09:47:05 */
/* http://harviacode.com */